spring:
  application:
    name: ch-kafka
  thymeleaf:
    mode: HTML5
    cache: false
  http:
    multipart:
      max-file-size: 20MB
#ZooKeeper
logging:
  config: classpath:config/logback.xml
  path: logs/${spring.application.name}
  level:
    com:
      ch: debug
share:
  path:
    libs: /mnt/share/common/libs
