spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    type: com.ch.jdbc.pool.ZhDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.10.66:3306/admin
    username: admin
    password: 123456
  thymeleaf:
    mode: HTML5
    cache: false
  http:
    multipart:
      max-file-size: 20MB
#ZooKeeper
dubbo:
  registry:
    address: 10.202.10.66:2181
logging:
  config: classpath:config/logback.xml
  path: logs/ch-sys
  level:
    com:
      ch: debug
share:
  path:
    upload: share/${spring.appliction.name}/upload
    libs: share/${spring.appliction.name}/libs
