spring:
  application:
    name: ch-kafka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://grdtest-m.dbsit.sfdc.com.cn:3306/grdtest
    username: grdtest
    password: admin123
  thymeleaf:
    mode: HTML5
    cache: false
  http:
    multipart:
      max-file-size: 20MB
#ZooKeeper
dubbo:
  registry:
    address: 10.202.107.137:2181
logging:
  config: classpath:config/logback.xml
  path: logs/ch-sys
  level:
    com:
      ch: debug
share:
  path:
    upload: share/${spring.application.name}/upload
    libs: share/${spring.application.name}/libs
