server:
  port: 7004

spring:
  application:
    name: ch-kafka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.250:30307/ch_mq?characterEncoding=UTF-8&serverTimezone=GMT
    username: admin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML5
    cache: false
logging:
  config: classpath:config/logback.xml
  path: logs/${spring.application.name}
  level:
    com:
      ch: debug
      alibaba: warn
share:
  path:
    upload: share/${spring.application.name}/upload
    libs: D:\\mnt\\share\\common\\libs
rocketmq:
  namesrv:
#    addr: 10.206.46.77:9876
    isVIPChannel: true
    consoleCollectData: D:\\tmp\\rocket\\console\\data
  console:
    data: D:\\tmp\\rocketmq-console\\data
  name-server: 10.206.46.77:9876 # 自己的RocketMQ服务地址
#  name-server: false
  producer:
    send-message-timeout: 300000
    group: ch-kafka
