apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-devops
  namespace: ch
  labels:
    app: ch-devops
  annotations:
    kubesphere.io/creator: zhimin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch-devops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ch-devops
    spec:
      containers:
        - name: container-xzcbje
          image: 'registry.kubeoperator.io:8082/ch/ch-devops:${DATETIME}'
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: >-
                -Dnacos.config.server-addr=nacos.public.svc.cluster.local:8848
                -Dnacos.config.namespace=4da0a4df-ea8e-4906-b53f-8e30884e1346
      imagePullSecrets:
        - name: ch-nexus